using UnityEngine;
using System.Collections;

public enum AdventurerAttack
{
    UninitializedVal = -1,
    None,
    MaceSwing,
    RainOfArrows,
    Bowshot,
    ShieldBlock,
    SpearThrust,
    Siphon,
    Haste,
    VampiricWinds,
    BurstOfSpeed,
    Inferno,
    Lightning,
    HammerBlow,
    GetBehindMe,
    Flanking,
    Rend,
    Bludgeon,
    ContinentSmash,
    Fortify,
    BloodOfSteel,
    WideSwing,
    CataclysmicImpact,
    Concuss,
    DreamlessSleep,
    QuickStab,
    Stiletto,
    ThroatSlit,
    BloodRites,
    BladeOfCrimson,
    FleetFeet,
    FlashStep,
    SecondSight,
    WithTheWind,
    HealingWind,
    BreathOfLife,
    Renewal,
    IceBullet,
    FrostSpear,
    CometStrike,
    ZoneOfSilence,
    SpeakNoEvil,
    AntiDrain,
    CovetNot
}
